apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: ecommerce
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "YOUR_ACCESS_KEY"     # Replace with your actual access key
  AWS_SECRET_ACCESS_KEY: "YOUR_SECRET_KEY"  # Replace with your actual secret key
  AWS_REGION: "us-east-1"                  # Replace with your desired region 