apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secrets
  namespace: ecommerce
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXM=  # base64 encoded "postgres"
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVJOSG9UUjZPODV6UzBzdzM2TWpHY2l0UmFkVzRrQlljY0E3dVVUS3lDWUdKbFM5MkdsV2xYcXFkbFZyN1VZa0VPM1RqdWJFRTZhazRjMXJxTGJSTGl3ZjAwWHhqemhQM3U=  # base64 encoded Stripe secret key
  STRIPE_PUBLIC_KEY: cGtfdGVzdF81MVJOSG9UUjZPODV6UzBzd3dFc284aTYxanJCVHByNXAzbkpwNldUejVoSjJlZXo5NW9vV0J3Mjd6WUxyRU42ZmJXdEw1WkZQNE8wd0NCZmR3NnIzT0VoQTAwcE44emp0VWM=  # base64 encoded Stripe public key 