name: Infrastructure CI/CD

on:
  push:
    paths:
      - 'infra/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'infra/**'
    branches: [ main ]

env:
  AWS_REGION: us-east-1

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: |
          cd infra/aws
          terraform init

      - name: Terraform Validate
        run: |
          cd infra/aws
          terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: |
          cd infra/aws
          terraform plan -out=tfplan
        continue-on-error: true

      - name: Comment Plan
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const output = `#### Terraform Plan 📝
            \`\`\`
            ${process.env.TF_PLAN || 'No changes. Infrastructure is up-to-date.'}
            \`\`\`
            `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            }) 